name: Release

on:
  push:
    branches:
      - pnpm

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # to publish a GitHub release
      issues: write # to comment on released issues
      pull-requests: write # to comment on released pull requests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read pnpm version from package.json
        id: pnpm_version
        run: echo "pnpm=$(jq -r '.engines.pnpm' package.json)" >> $GITHUB_ENV

      - name: pnpm actions setup
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm" # Enable pnpm caching

      - name: Verify pnpm installation
        run: pnpm --version

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: pnpm run release
